[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
description = "A concurrent arena providing mutually exclusive access over guarded indexes"
documentation = "https://docs.rs/arena64"
license = "MIT"
name = "arena64"
repository = "https://github.com/Bajix/arena64"
readme = "./README.md"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = { version = "1.20", default-features = false, features = ["race", "alloc"] }

[features]
# Enable unstable `strict_provenance` language feature. See tracking issue: https://github.com/rust-lang/rust/issues/95228
strict_provenance = []
