[package]
authors = ["Thomas Sieverding <Thomas@bajix.com>"]
description = "A concurrent arena providing mutually exclusive access over guarded indexes"
documentation = "https://docs.rs/arena64"
license = "MIT"
name = "arena64"
repository = "https://github.com/Bajix/arena64"
readme = "./README.md"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
